fuseml/fuseml-core

cmd/fuseml_core/http.go, go.mod, go.sum
Replaces the defaults response encoder and request decoder with
functions that returns a YAML encoder/decoder when no content-type
is provided or content-type is `application/x-yaml`. In case of a
different content type, returns the default encoder/decoder provided
by Goa.
Fixes: fuseml/fuseml#58
=> Add support for YAML as media type for the fuseml-core

cmd/fuseml_core/main.go, pkg/core/codeset_store.go, pkg/core/runnable_store.go, pkg/domain/codeset.go, pkg/domain/runnable.go, pkg/svc/codeset.go, pkg/svc/openapi.go, pkg/svc/runnable.go
* dependency inversion principle: runnable in-memory store
implementation is decoupled from the core by means of interfaces
and dependency injection
* moved HTTP server handler services to separate package
* renamed fuseml package to core package
=> Refactored artifact store implementation

pkg/core/codeset_store.go, pkg/core/gitea/client.go, pkg/core/gitea/client_test.go
PrepareRepository has additional argument pointing to listener
URL. If it is nil, webhook will not be created.
This is just initial idea. I think in the end, CreateRepoWebhook or EditRepoWebhook needs to be part of the API, so that whoever wants to modify it, do not need to access gitea client directly.
=> Make the creation of webhook optional when creating codeset

pkg/core/codeset_store.go, pkg/core/gitea/client.go, pkg/domain/codeset.go
So that users of Codeset can create webhook without the need
to access git client module directly
=> Added CreateWebhook as a method for CodesetStore

cmd/fuseml_core-cli/http.go, cmd/fuseml_core/http.go
Due to the issue with the YAML enconder/decoder, where it basically sets
all key to lower case, change the default enconder/decoder back to JSON.
=> Set the default encoder/decoder back to JSON

pkg/core/gitea/client.go
The labels, description and URL were missing for codeset list.
=> fix: Fill missing codeset fields

pkg/core/codeset_store.go, pkg/core/config/config.go
Remove the variable StagingEventListenerURL with fixed value,
Codesets should rather have webhook defined once they are assigned
to a workflow.
=> Do not create default webhook when Codeset is created

go.mod, go.sum, pkg/core/tekton/tekton.go, pkg/core/tekton/tekton_test.go, pkg/core/tekton/testdata/tekton-event-listener.yaml, pkg/core/tekton/testdata/tekton-pipeline-run.yaml, pkg/core/tekton/testdata/tekton-pipeline.yaml, pkg/core/tekton/testdata/tekton-trigger-binding.yaml, pkg/core/tekton/testdata/tekton-trigger-template.yaml, pkg/core/tekton/testdata/workflow.yaml, pkg/svc/workflow.go
Add unit tests for the public tekton workflow backend functions.
This change also makes waiting for the event listener optional when creating it.
=> Add unit tests for tekton workflow backend

pkg/core/tekton/constants.go, pkg/core/tekton/tekton.go, pkg/core/tekton/testdata/tekton-pipeline.yaml
So that containers of tekton tasks could use them.
See e.g. https://github.com/fuseml/extensions/pull/1
Part of https://github.com/fuseml/fuseml/issues/75
=> Export Workflow name and namespace to the tekton tasks

pkg/core/gitea/client.go
User who creates the codeset might be different one than
user who is creating tekton pipeline (which needs to clone the code).
To prevent authentication issues, let's make the repository public.
See https://github.com/fuseml/fuseml/issues/89
=> Codeset: do not create repository as private

cmd/fuseml_core-cli/main.go, design/codeset.go, pkg/core/codeset_store.go, pkg/core/gitea/client.go, pkg/core/gitea/client_test.go, pkg/core/tekton/tekton.go, pkg/core/tekton/tekton_test.go, pkg/domain/codeset.go, pkg/svc/codeset.go, pkg/svc/workflow.go
Model the codeset attributes that need to be supplied when
registering a codeset as CLI command line arguments.
This change also requires defining a separate domain data type
for a codeset record, which further decouples the REST API
layer from the internal core logic used to manage codesets.
=> Codesets: add arguments to 'codeset register' CLI command

design/workflow.go, pkg/svc/workflow.go
Makes using the CLI easier as it accepts passing the parameters
directly instead of building a body when assigning workflows to
codesets.
=> Add `Param`s to workflow assign

pkg/core/gitea/client_test.go, pkg/core/tekton/tekton.go
* client_test.go: exported func NewTestGiteaAdminClient returns unexported
type *gitea.giteaAdminClient, which can be annoying to use
* tekton.go: redundant type from array, slice, or map composite literal
=> Fix some golint warnings

go.mod, go.sum, pkg/client/git.go
To make sure the source directory is not modified (by initializing
git repository in it), do the git push operations in separate
temporary directory instead.
=> Git client: copy the source codeset directory to tmpdir

cmd/fuseml_core-cli/http.go, cmd/fuseml_core-cli/main.go, design/api.go, design/cli/cli.go, design/cli/http.go, go.sum
Introduces a goa plugin used to generate CLI code with fuseml customizations. It is based on the original CLI client code taken from goa. The PR also includes customizations:
* switched to YAML as the body format used for the CLI commands
* enabled strict checking for YAML encoder (duplicate keys and unknown keys are signalled as errors now)
=> Customized goa CLI code generator 

cmd/fuseml_cli/main.go
This way user does not have to provide -url option for every client invocation.
Next time will add a support for config file, but this is tiny change that already helps...
=> Allow setting server URL via environment variable FUSEML_SERVER_URL

Makefile
- Adds test to the release target
- Adds `client_release` to `release_all` target
- Build binaries for the same architectures as fuseml-installer.
=> release: Add test to release and sync archs with fuseml-installer

.github/workflows/release.yml
Add a new job to the release workflow to build and push the fuseml-core
docker image.
The image name and tag is derived from the repository name and the release
tag respectively.
The job also runs for push events on the main branch which will push a docker
image with the `dev` tag.
Fixes: https://github.com/fuseml/fuseml/issues/105
=> Add job to build/publish docker image on release workflow

Makefile
This is because of untar method we are using by installer does not
seem to be supported on Windows.
I do not know if this is the right approach. Alternatively we could
- use some more windows friendly archive (zip)
- do not archive any binary to be consistent
=> Archive windows binary with zip

go.mod, pkg/cli/cmd.go, pkg/cli/common/client.go, pkg/cli/common/global.go
Due to a known limitation in the viper library [1], binding
cobra flags to a go variable and to a viper environment
variable at the same time is not supported.
This commit implements a workaround [2] that updates the flags
according to information extracted by viper from env variables
and configuration files after the cobra logic has finished loading
the flag variables.
The commit also adds support for using an optional fuseml CLI
configuration file where global configuration parameter values
can be stored. This is a yaml file that can be located either at
`$PWD/.fuseml/config.yaml` or at `$HOME/.fuseml/config.yaml`.
The priority in which configuration options are loaded is:
1. explicit set via command line args
2. environment variable
3. configuration file
4. default flag value
The PR …
=> CLI: Fixed handling of env variables for global options

README.md, design/codeset.go, pkg/cli/codeset/register.go, pkg/cli/git/git.go, pkg/core/codeset_store.go, pkg/core/gitea/client.go, pkg/core/gitea/client_test.go, pkg/domain/codeset.go, pkg/svc/codeset.go
```
> fuseml codeset register --name test03 --project mlflow-project-02 --location /tmp/mlflow/empty
codeset:
name: test03
project: mlflow-project-02
description: ""
labels: []
url: ""
username: fuseml-mlflow-project-02
password: NfHK5a84jjJkwzDk
2021/05/26 16:47:21 Pushing the code to the git repository...
```
TODO
I changed the names of `GITEA_` env variables: this will require change in fuseml-installer too.
=> When user is created for a project, return name and password

design/workflow.go, pkg/cli/git/git.go, pkg/core/codeset_store.go, pkg/core/gitea/client.go, pkg/core/gitea/client_test.go, pkg/core/tekton/tekton.go, pkg/core/tekton/tekton_test.go, pkg/core/workflow_store.go, pkg/domain/codeset.go, pkg/domain/workflow.go, pkg/svc/workflow.go
This PR adds support for the workflow unassign and delete operations. Besides the changes to workflows, the following changes were made to codesets:
- Adds a function to delete webhook from codeset and update the create
webhook function to also return the created webhook ID.
- Delete `.git` directory before performing `git init` when registering a codeset. This ensures that git initialises correctly when pushing code that is already versioned by git.
TBD:
=> Implements workflow unassign and delete

pkg/core/tekton/tekton.go, pkg/core/tekton/tekton_test.go, pkg/domain/workflow.go, pkg/svc/workflow.go
Assigning a workflow to a codeset consists of creating 3 tekton resources
(trigger template, trigger binding and event listener).
In case of a failure during the creation, delete any previously created resource.
=> Delete resources in case of partial failure on workflow assign

pkg/cli/application/delete.go, pkg/cli/application/get.go, pkg/cli/application/list.go, pkg/cli/client/common.go, pkg/cli/client/workflow.go, pkg/cli/codeset/delete.go, pkg/cli/codeset/get.go, pkg/cli/codeset/list.go, pkg/cli/codeset/register.go, pkg/cli/common/formatting.go, pkg/cli/runnable/get.go, pkg/cli/runnable/list.go, pkg/cli/runnable/register.go, pkg/cli/workflow/assign.go, pkg/cli/workflow/create.go, pkg/cli/workflow/get.go, pkg/cli/workflow/list.go, pkg/cli/workflow/list_assignments.go, pkg/cli/workflow/list_runs.go, pkg/cli/workflow/utils.go
- Add the `text` output format, this format should be used when a command
has its own custom format for the output.
- Moves all the workflow functions that interacts with the API to
a client package under pkg/cli/common.
- Implements a custom format bsed on a template for the workflow get
command. The output format is inspired by the tekton CLI.
=> CLI: Add `text` format and implement `text` output for workflow get 

design/workflow.go, pkg/cli/client/workflow.go, pkg/cli/workflow/assign.go, pkg/cli/workflow/cmd.go, pkg/cli/workflow/delete.go, pkg/cli/workflow/list_runs.go, pkg/cli/workflow/unassign.go, pkg/core/gitea/client.go, pkg/svc/workflow.go
- API: change workflow register to workflow create
- fix: when creating a webhook if it already exists return its ID instead of nil
- CLI: fix the order of codeset name and project parameters to be the same for all commands that needs it
- CLI: Implements the workflow unassign and delete commands.
=> CLI: Implements workflow unassign/delete and other minor fixes

pkg/cli/workflow/list_runs.go, pkg/cli/workflow/utils.go, pkg/core/tekton/tekton.go
When listing workflow runs just after a workflow run starts it fails
as there is no start time on it yet, resulting in a nil pointer dereference
error.
This change adds checks for the start time before trying to reference
it.
=> fix: listing workflow runs just after assign fails

Dockerfile
Copy the openapi files from the builder step to the fuseml-core docker
image.
=> Add generated openapi files to fuseml-core docker image

cmd/fuseml_core/grpc.go, cmd/fuseml_core/http.go, cmd/fuseml_core/main.go, design/api.go, design/project.go, pkg/cli/client/common.go, pkg/cli/client/project.go, pkg/cli/cmd.go, pkg/cli/codeset/cmd.go, pkg/cli/codeset/register.go, pkg/cli/codeset/set.go, pkg/cli/common/global.go, pkg/cli/git/git.go, pkg/cli/project/cmd.go, pkg/cli/project/create.go, pkg/cli/project/delete.go, pkg/cli/project/get.go, pkg/cli/project/list.go, pkg/cli/project/set.go, pkg/core/codeset_store.go, pkg/core/gitea/client.go, pkg/core/gitea/client_test.go, pkg/core/project_store.go, pkg/domain/project.go, pkg/svc/project.go
When CurrentProject is set in .fuseml/config.yaml, commands normally requiring "--project" option will use CurrentProject when "--project" is not provided.
implementation of https://github.com/fuseml/fuseml/issues/118
Example of `.fuseml/config.yaml` (note that it's not case sensitive):
```
currentcodeset: mlflow-02
currentproject: mlflow-project-02
url: http://localhost:8000
currentuser: fuseml-mlflow-project-02
currentpassword: newpassword
```
It's just one level for now, we can make it more structured if we find it useful.
The priorities go like: CLI option > env variable > config file under current directory > config file under $HOME
=> Implement support for Projects and defaults for user, password and codeset

cmd/fuseml_core/main.go, design/workflow.go, pkg/core/manager/workflow.go, pkg/core/manager/workflow_test.go, pkg/core/tekton/tekton.go, pkg/core/tekton/tekton_test.go, pkg/core/workflow_store.go, pkg/domain/workflow.go, pkg/svc/workflow.go
WorkflowManager provides functions for managing workflows. Any operation
that needs to interact with the workflow store and backend should be done
through the functions offered by the WorkflowManager as it should be the only
object that interfaces with both.
The idea is for the Workflow service to consume the functions provided by the
Workflow Manager when it needs to perform operations on the workflow store/backend,
instead of directly calling the workflow store/backend and building the logic around
them. This does not only provider better control over the store/backend, but also moves
the logic away from the service to the workflow manager.
This PR also includes some improvements workflows:
- Add `logger` to the Tekton WorkflowBackend struct and remove it from its functions.
- On …
=> workflow: Add workflow manager and some improvements

pkg/cli/cmd.go, pkg/cli/codeset/set.go, pkg/cli/common/global.go, pkg/cli/common/util.go, pkg/cli/project/set.go
This is a workaround for https://github.com/spf13/viper/issues/433;
once it is fixed, viper.WriteConfig should be able to create the config
file if it does not exist.
=> Make sure config file exists before attempting to write it

Makefile
Currently, the binaries version are always being resolved to the latest
tag, independent on the branch/tag where the code is being compiled.
This change fixes that by trying to resolve the version from the branch
name and, if not possible, then use the tag name.
=> fix: set correct version when compiling on branch

pkg/core/codeset_store.go, pkg/core/manager/workflow.go, pkg/core/manager/workflow_test.go, pkg/domain/codeset.go
When a codeset is deleted and it has a workflow assigned to it, also
unassign the workflow from the codeset.
To perform that without creating a cyclic dependency between workflow
manager and codeset store, a pub/sub scheme was created. This allows
codeset store to notify workflow manager when a codeset that has
a workflow assigned to it is being deleted. With that notification
the workflow manager performs the unassign from the workflow to the
codeset being deleted.
Fixes: fuseml/fuseml#113
=> fix: Unassign workflow when deleting assigned codeset

pkg/core/tekton/constants.go, pkg/core/tekton/tekton.go, pkg/core/tekton/testdata/tekton-event-listener.yaml, pkg/core/tekton/testdata/tekton-pipeline-run.yaml, pkg/core/tekton/testdata/tekton-trigger-template.yaml
Instead of sharing the same service account, use different service
accounts for the event listener and running the workflows. This allows
configuring the service account's permissions specifically for each
case.
Depends-on: https://github.com/fuseml/fuseml/pull/172
=> tekton: Use different service accounts for triggers and pipelines

design/extension.go, pkg/cli/client/extension.go, pkg/svc/extension.go
The URL endpoint attribute is used as a URL path token, which means
it needs to be URL-escaped by the CLI and URL-unescaped by the server.
Unfortunately, goa doesn't support this use-case, and worse, handling
the URL-escaping outside of goa clashes with the URL format
validation.
This commit removes the URL format validation for the endpoint URL
field and handles the URL escaping in the CLI/server code.
=> extensions: fix endpoint URL encoding

design/workflow.go, pkg/cli/workflow/list_runs.go, pkg/core/tekton/tekton.go
- design: Removes the `Enum` filter as the status can also returns
a workflow failure reason.
- when a workflow run fails report its status as `Failed (reason)`.
Fixes: https://github.com/fuseml/fuseml/issues/221
=> Fix workflow list runs when status is a failed reason

.github/workflows/release.yml, Dockerfile, Makefile
Use docker buildx [1] to build a multi-arch docker image for
fuseml-core.
[1] https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images
Closes fuseml/fuseml#207
=> Build multi-arch fuseml-core docker image

pkg/core/extension_store.go, pkg/core/manager/extension.go, pkg/core/manager/extension_test.go, pkg/core/manager/workflow.go, pkg/core/manager/workflow_test.go, pkg/domain/extension.go, pkg/svc/extension.go
- Add `Services` field to `Extension` to store services pertaining to
the extension.
- Add `Credentials` and `Endpoints` field to `ExtensionService` to store
credentials and endpoints pertaining to the service.
- Removed *Record types as the relation between extensions, services,
credentials and endpoints are represented by the repective types.
- Removed *ID types as there is no use for the "parent" IDs.
- Moved most of the `Extension` behaviour logic out of the extension
store to the `Extension` domain.
- Renamed types:
- `ExtensionEndpoint` to `ExtensionServiceEndpoint`
- `ExtensionCredentials` to `ExtensionServiceCredentials`
=> Refactor Extensions

.github/workflows/release.yml, Dockerfile, Makefile
Use docker buildx [1] to build a multi-arch docker image for
fuseml-core.
[1] https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images
Closes fuseml/fuseml#207
Backports: #107
=> [0.2] Build multi-arch fuseml-core docker image

design/workflow.go, pkg/cli/workflow/list_runs.go, pkg/core/tekton/tekton.go
- design: Removes the `Enum` filter as the status can also returns
a workflow failure reason.
- when a workflow run fails report its status as `Failed (reason)`.
Fixes: https://github.com/fuseml/fuseml/issues/221
Backports: #105
=> [0.2] Fix workflow list runs when status is a failed reason

Dockerfile
When defining ARG all caches from stages that uses `ARG` and
`RUN`s are invalidated.
This change moves the ARG definition to just before it is used so
it does not invalidate cache from the previous layers.
More info at: https://docs.docker.com/engine/reference/builder/#impact-on-build-caching
=> Dockerfile: Define `ARG` just before it is used

pkg/core/extension_store.go, pkg/core/manager/extension.go, pkg/core/manager/extension_test.go, pkg/core/manager/workflow.go, pkg/core/manager/workflow_test.go, pkg/domain/extension.go, pkg/svc/extension.go
- Add `Services` field to `Extension` to store services pertaining to
the extension.
- Add `Credentials` and `Endpoints` field to `ExtensionService` to store
credentials and endpoints pertaining to the service.
- Removed *Record types as the relation between extensions, services,
credentials and endpoints are represented by the repective types.
- Removed *ID types as there is no use for the "parent" IDs.
- Moved most of the `Extension` behaviour logic out of the extension
store to the `Extension` domain.
- Renamed types:
- `ExtensionEndpoint` to `ExtensionServiceEndpoint`
- `ExtensionCredentials` to `ExtensionServiceCredentials`
Backports: #100
=> [0.2] Refactor Extensions

Dockerfile
When defining ARG all caches from stages that uses `ARG` and
`RUN`s are invalidated.
This change moves the ARG definition to just before it is used so
it does not invalidate cache from the previous layers.
Backports: #109
=> [0.2] Dockerfile: Define ARG just before it is used

design/workflow.go, pkg/core/tekton/builder/task_spec.go, pkg/core/tekton/tekton.go, pkg/core/tekton/testdata/tekton-pipeline.yaml, pkg/core/tekton/testdata/workflow.yaml, pkg/domain/workflow.go, pkg/svc/workflow.go
The `resources` field can be used to specify kubernetes resources
requests and limits for container that runs the step.
Fix: https://github.com/fuseml/fuseml/issues/261
=> Workflow: Add `resources` field to step
